### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gxh-apologize** [simplepeng/Updater#4]
使用该库的时候报错，请问是什么原因，如下：  
安卓7.1  商米收银机

  java.lang.RuntimeException: Unable to start receiver com.simplepeng.updaterlibrary.DownloadReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3047)
        at android.app.ActivityThread.-wrap18(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:584)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:558)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
        at com.simplepeng.updaterlibrary.DownloadReceiver.installApk(DownloadReceiver.java:81)
        at com.simplepeng.updaterlibrary.DownloadReceiver.queryFileUri(DownloadReceiver.java:61)
        at com.simplepeng.updaterlibrary.DownloadReceiver.onReceive(DownloadReceiver.java:30)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3040)
        at android.app.ActivityThread.-wrap18(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by simplepeng** [comment]
@gxh-apologize 用的哪一个版本呢？

**Comment by gxh-apologize** [comment]
1.0.2

**Comment by simplepeng** [comment]
@gxh-apologize 更换为1.0.3试试，之前修复了一些bug
